
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jango-fett.bukukas.io
  resources:
  - elasticsearches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jango-fett.bukukas.io
  resources:
  - elasticsearches/finalizers
  verbs:
  - update
- apiGroups:
  - jango-fett.bukukas.io
  resources:
  - elasticsearches/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - jango-fett.bukukas.io
  resources:
  - environments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jango-fett.bukukas.io
  resources:
  - environments/finalizers
  verbs:
  - update
- apiGroups:
  - jango-fett.bukukas.io
  resources:
  - environments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - jango-fett.bukukas.io
  resources:
  - postgresqls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jango-fett.bukukas.io
  resources:
  - postgresqls/finalizers
  verbs:
  - update
- apiGroups:
  - jango-fett.bukukas.io
  resources:
  - postgresqls/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - rolebindings
  - roles
  verbs:
  - '*'
